## Pytorch

Numpy'da olduğu gibi Pytorch kütüphanesi kullanılarak bilimsel hesaplamalar yapılabilir.

Pytorch'un Numpy'dan farkı, Pytorch'da GPU gücünü kullanabiliyoruz. Pytorch'u GPU üzerinden koşturabiliyoruz yani bilgisayarın ekran kartını kullanabiliyoruz.

Pytorch esneklik ve hız sağlar. Yapılan araştırmalara göre Pytorch, Keras ve Tensorflow'dan daha hızlıdır ve zamanda esneklik sağlar. Esneklikten kasıt şudur: Pytorch'da küçük birimlere kadar dizaynı kendimiz yapıyoruz. Yani neural netwok'ün en küçük birimlerine kadar dizaynı kendimiz yapabiliyoruz.

Pytorch'da debugging işlemi çok kolaydır. Bu özelliği Pytorch'un kullanımın yaygınlaşmasına sebep olan önemli özelliklerinden birisidir.

## Matrices

Matrisler, değerleri içerisinde barındıran array'lerdir. Array'leri neden neural network'te kullanıyoruz ya da neden pytorch'da öğreniyoruz? Herhangi bir neural network yapısını düşünün. İlk aşama forward propagation'dur. Yani prediction işleminin gerçekleştirildiği adımdır. Prediction işlemini gerçekleştirdikten sonra elimizdeki loss değerine göre backward propagation ile parametreleri update ediyoruz ve böylece öğrenme işlemini gerçekleştiriyoruz. 

Prediction denilen işlem matrislerin birbirleriyle çarpılıp toplanması sonucunda ortaya çıkan bir değerdir. Parametre denilen şey matrislerdir. Bu nedenle matrisler neural network'ün temel yapı taşlarıdır.

<font color="CornflowerBlue"><br>
Pytorch'da matrisler 'tensor' olarak adlandırılır. Sadece Pytorch'da değil, array'ler tensor olarak adlandırılabilir. Tensor, multi dimension array'lerdir. Matrisler 2 boyutlu array'lerdir. 3,4,5... şeklinde multi dimension array'ler olduğunda "3 boyutlu array" veya "tensor" şeklinde adlandırabiliriz.
    
<br>
<img src="p1.png" align = "left" style="width:400px;height:300px"/>

Şimdi numpy kütüphanesi ile array tanımlayalım. Ve numpy'dan pytorch kütüphanesine geçiş yapalım.

In [1]:
import numpy as np

# numpy array
array = [[1,2,3],[4,5,6]]
first_array = np.array(array) # 2x3 array
print("Array Type: {}".format(type(first_array))) # type
print("Array Shape: {}".format(np.shape(first_array))) # shape
print(first_array)

Array Type: <class 'numpy.ndarray'>
Array Shape: (2, 3)
[[1 2 3]
 [4 5 6]]


array = [[1,2,3],[4,5,6]] satırında bir liste elde edilmiştir. 

first_array = np.array(array) satırında liste, numpy array'e çevrilmiştir.

Şimdi de pytorch array implement edelim.

In [2]:
# import pytorch library
import torch

# pytorch array
tensor = torch.Tensor(array)
print("Array Type: {}".format(tensor.type)) # type
print("Array Shape: {}".format(tensor.shape)) # shape
print(tensor)

Array Type: <built-in method type of Tensor object at 0x000002A5F5A361D0>
Array Shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


tensor = torch.Tensor(array) satırı ile array isimli listeyi tensor yapısına dönüştürdüm.

Şimdi allocation'un nasıl yapıldığından bahsedeyim. Bir tane boş liste oluşturup buna append etmektense belli boyutlarda matris yani tensor oluştururuz ve istediğimiz dedğerleri bu tensor'un içerisine depolarız. Böylece memory'den yer ayırmış oluyoruz ve buda işlemleri hızlı yapmamızı sağlar. Numpy'da bunu çok kullanıyoruz ve şimdi Pytorch'da nasıl kullanacağımızı görelim.

<font color="IndianRed"><br>
np.ones() = torch.ones()

<font color="IndianRed"><br>
np.random.rand() = torch.rand()

Renkli ifadelerde numpy'da yapılan bazı işlemlerin torch'da nasıl yapıldığını görmektesiniz. 

np.ones() = torch.ones() satırında np.ones() ifadesi ile 1 değerlerinden oluşan bir matris elde edilir. Bu işlemin torch'daki karşılığı torch.ones() şeklindedir.

np.random.rand() = torch.rand() satırında ise, numpy'da random sayılar oluşturmak için np.random.rand() ifadesini kullanırız. Bu işlemin torch'daki karşılığı torch.rand() 'dır.

Şimdi bu işlemlere dair bir kod yazalım.

In [3]:
# numpy ones
print("Numpy {}\n".format(np.ones((2,3))))

# pytorch ones
print(torch.ones((2,3)))

Numpy [[1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.]])


np.ones((2,3)) ifadesi ile 2x3 boyutunda 1 değerlerinden oluşan bir array oluşturulmuştur. Bu işlemin torch'daki karşılığı torch.ones((2,3)) şeklinde gerçekleştirilmiştir.

In [4]:
# numpy random
print("Numpy {}\n".format(np.random.rand(2,3)))

# pytorch random
print(torch.rand(2,3))

Numpy [[0.64805633 0.73986846 0.39393477]
 [0.69137843 0.53298923 0.27668312]]

tensor([[0.9833, 0.5280, 0.2522],
        [0.5085, 0.6267, 0.9850]])


Yukarıda görüldüğü üzere 2x3 boyutunda random değerleden oluşan array'ler numpy ve torch ile elde edilmiştir.

Bir işlemin numpy'da nasıl yapıldığını bilip, torch'da nasıl yapıldığını bilmiyorsanız şöyle bir çözüm önerebilirim: İşlemleri numpy ile yapın ve en son neural network'ün input'unu pytorch'a çevirin ve neural network'ü eğitmeye başlayın. Bu işlemi şöyle yapıyoruz: 

torch.from_numpy()

kod satırı ile numpy kütüphanesinden pytorch kütüphanesine çevrim gerçekleştirilebiliyor.

numpy()  

kod satırı ile de pytorch'dan numpy'a dönüşüm yapabiliyoruz.

In [6]:
# random numpy array
array = np.random.rand(2,2)
print("{} {}\n".format(type(array),array))

# from numpy to tensor
from_numpy_to_tensor = torch.from_numpy(array)
print("{}\n".format(from_numpy_to_tensor))

# from tensor to numpy
tensor = from_numpy_to_tensor
from_tensor_to_numpy = tensor.numpy()
print("{} {}\n".format(type(from_tensor_to_numpy),from_tensor_to_numpy))

<class 'numpy.ndarray'> [[0.23952739 0.24717972]
 [0.59226599 0.41134401]]

tensor([[0.2395, 0.2472],
        [0.5923, 0.4113]], dtype=torch.float64)

<class 'numpy.ndarray'> [[0.23952739 0.24717972]
 [0.59226599 0.41134401]]



array = np.random.rand(2,2) satırında numpy kütüphanesine ait bir array oluşturulmuştur.

from_numpy_to_tensor = torch.from_numpy(array) satırında array numpy kütüphanesinden pytorch kütüphanesine döndürülmüştür.

Elimizde pytorch'a ait tensor var. 

tensor = from_numpy_to_tensor

from_tensor_to_numpy = tensor.numpy()

satırlarında tensor'den numpy kütüphanesinin array'lerine dönüş yapılmıştır.

## Basic Math with Pytorch

In [7]:
# create tensor 
tensor = torch.ones(3,3)
print("\n",tensor)

# Resize
print("{}{}\n".format(tensor.view(9).shape,tensor.view(9)))

# Addition
print("Addition: {}\n".format(torch.add(tensor,tensor)))

# Subtraction
print("Subtraction: {}\n".format(tensor.sub(tensor)))

# Element wise multiplication
print("Element wise multiplication: {}\n".format(torch.mul(tensor,tensor)))

# Element wise division
print("Element wise division: {}\n".format(torch.div(tensor,tensor)))

# Mean
tensor = torch.Tensor([1,2,3,4,5])
print("Mean: {}".format(tensor.mean()))

# Standart deviation (std)
print("std: {}".format(tensor.std()))


 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([9])tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

Addition: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

Subtraction: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Element wise multiplication: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Element wise division: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Mean: 3.0
std: 1.5811388492584229


tensor = torch.ones(3,3) satırında 3x3 boyutunda 1 değerlerinden oluşan bir tensor oluşturulmuştur.

print("{}{}\n".format(tensor.view(9).shape,tensor.view(9))) satırında 3x3 boyutundaki tensor 1x9'luk vektör haline getirilmiştir.

print("Addition: {}\n".format(torch.add(tensor,tensor))) satırında 2 tane tensor toplanmıştır.

print("Subtraction: {}\n".format(tensor.sub(tensor))) satırında çıkarma işlemi yapılmıştır.

print("Element wise multiplication: {}\n".format(torch.mul(tensor,tensor))) satırında tensorlerin çarpımı gerçekleştirilmiştir.

print("Element wise division: {}\n".format(torch.div(tensor,tensor))) satırında bölme işlemi gerçekleştirilmiştir.

tensor = torch.Tensor([1,2,3,4,5])
print("Mean: {}".format(tensor.mean())) satırında ortalama hesaplanmıştır.

print("std: {}".format(tensor.std())) satırında standart sapma hesaplanmıştır.

## Variables

Variables, gradient'leri içerisinde toplayan, biriktiren, depolayan yapılardır.

Variables ile Array'ler arasındaki fark şudur:

Variable'ler biz bir türev aldığımız zaman, gradient'i hesapladığımız zaman bu gradient'i içerisinde barındıran yapılardır.

Tesnor'lerde olduğu gibi variable'lerde de matematiksel işlemleri gerçekleştirebiliyoruz. Backward propagation yapabilmek için yani neural network kurabilmek için, neural network'ü eğitebilmek için pytorch'da variable'lere ihtiyaç vardır.

<br>
<img src="p2.png" align = "left" style="width:500px;height:200px"/>

Şimdi bir matematiksel örnek yapalım.

Assume we have equation y = x^2

Define x = [2,4] variable

After calculation we find that y = [4,16] (y = x^2)

Recap o equation is that o = (1/2)sum(y) = (1/2)sum(x^2)

deriavative of o = x

Result is equal to x so gradients are [2,4]

Lets implement

Yukarıdaki işlemleri açıklayayım. y=x^2 şeklinde bir denklem vardır. x, 2 ve 4 değerlerini alabilmektedir. y'yi hesaplamak için 2 ve 4'ü yerine koymalıyız. y'yi 4 ve 16 buluruz. o = (1/2)sum(y) = (1/2)sum(x^2) satırında o isimli bir variable tanımlanarak toplama işlemi gerçekleştirilmiştir. Sonrasında o'yu kullanarak x'e göre gradient alınır. Yani o'nun x'e göre türevi alınacaktır.

Bu işlemleri görsel üzerinden ifade edelim:

<br>
<img src="p3.png" style="width:500px;height:200px"/>

Şimdi bu işlemleri pytorch ile implement edelim.

In [8]:
# import variable from pytorch library
from torch.autograd import Variable

# define variable
var = Variable(torch.ones(3), requires_grad = True)
var

tensor([1., 1., 1.], requires_grad=True)

Yukarıdaki from torch.autograd import Variable kod satırı ile variables import edilmiştir.

var = Variable(torch.ones(3), requires_grad = True) satırında ise torch.ones(3) parametresi ile 1'lerden oluşan bir tensör oluşturulmuştur ve Variable'nin içerisine atılmıştır. requires_grad = True parametresi ile gradient bulma işlemi yapılacağı bildirilerek variable'ler ona göre ayarlanmıştır.

Şimdi yukarıda yaptığımız matematiksel örneği koda dökelim.

In [9]:
array = [2,4]
tensor = torch.Tensor(array)
x = Variable(tensor, requires_grad = True)
y = x**2
print(" y =  ",y)

# recap o equation o = 1/2*sum(y)
o = (1/2)*sum(y)
print(" o =  ",o)

# backward
o.backward() # calculates gradients

print("gradients: ",x.grad)

 y =   tensor([ 4., 16.], grad_fn=<PowBackward0>)
 o =   tensor(10., grad_fn=<MulBackward0>)
gradients:  tensor([2., 4.])
